### ISSUE TITLE
[POM] Добавить зависимости для fasterxml

### ISSUE THREAD

**Issue by das13** [pnvictoria/Freelance_Spring_MVC#3]
Проект не деплоится без fasterxml.
Необходимо добавить соотв-ю зависимость.

**Comment by pnvictoria** [comment]
Подскажите, пожалуйста, какая именно зависимость, потому что у меня вроде бы все нормально билдится и деплоится на Weblogic.

**Comment by das13** [comment]
fasterxml
Имеется в виду вот эта
```
<dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.9.4</version>
</dependency>
```
Если попытаться собрать Мавеном, то проект без нее не соберется (у меня не собирается)
